### ISSUE TITLE
nav-mesh + jump-ability ? 

### ISSUE THREAD

**Issue by petrovicstefanrs** [donmccurdy/aframe-physics-system#102]
Is it possible to add jump ability to player and use navmesh as ground player can jump to?

**Comment by donmccurdy** [comment]
Currently no, this isn't possible — the `jump-ability` component depends on physics and not the navmesh system. It would certainly be possible to write another jump component that uses a navmesh instead.

**Comment by petrovicstefanrs** [comment]
Great, thanks for the info, I suppose I could look into writing a jump component that depends on navmesh.

**Comment by EricEisaman** [comment]
@petrovicstefanrs Any luck with writing a jump component that depends on navmesh?
