### ISSUE TITLE
problems in chrome 

### ISSUE THREAD

**Issue by imgntn** [donmccurdy/aframe-physics-system#11]
the example doesn't seem to work in latest webVR chrome Version 56.0.2902.0 (64-bit)

i briefly see dynamic bodies before sim starts then they just disappear and all of the positions and rotations end up as NaN

things work as expected in firefox nightly and it works in release chrome without VR Version 55.0.2883.87 m (64-bit)

perhaps related to bad time values in this release of webVR chrome https://github.com/aframevr/aframe/issues/2207

**Comment by machenmusik** [comment]
per discussion on aframevr/aframe#2217 it seems that a workaround for chromium would need to be done outside aframe core

**Comment by wmurphyrd** [comment]
The previous build of WebVR Chromium ([Sep 23](https://drive.google.com/open?id=0BzudLt22BqGRbHdGOTdiaTBkZXM)) will work while we wait for a fixed build, and you can check for the offending browser with:

    window.hasNativeWebVRImplementation && navigator.userAgent.includes('Chrome/56')


if you want to notify users.

**Comment by machenmusik** [comment]
thx - however Sep23 build does not include Oculus Touch support, and a few other things.  Core team has clearly stated they will not accept systemic workarounds for one-off browser flaws, so until new Chromium builds fix it, components will have to fix themselves (as was done for controllers as part of #2192)

**Comment by donmccurdy** [comment]
Latest version of Chromium is back to normal. 🎊
