### ISSUE TITLE
Adding a spring component

### ISSUE THREAD

**Issue by gftruj** [donmccurdy/aframe-physics-system#112]
The Cannon.Spring seems to be a simple addition.

@donmccurdy let me know if you'd like me to add it as a simple component (already done it, check it out on my fork [here](https://github.com/gftruj/aframe-physics-system/blob/feat-spring-component/src/components/spring.js), example [here](https://cdn.rawgit.com/gftruj/aframe-physics-spring/f2899bc3/example/spring.html))

If You'd like, i can make a PR out of my [branch](https://github.com/gftruj/aframe-physics-system/tree/feat-spring-component), otherwise I'd keep it as a separate [component](https://github.com/gftruj/aframe-physics-spring)

**Comment by gftruj** [comment]
Thanks :grin: 
Got a couple of deadlines this week, I'll try to make a PR at the weekend :)

**Comment by donmccurdy** [comment]
Fixed at https://github.com/donmccurdy/aframe-physics-system/pull/114.
