### ISSUE TITLE
Setting restitution of individual objects

### ISSUE THREAD

**Issue by rrrepos** [donmccurdy/aframe-physics-system#115]
From what I can see, the `restitution` property is set at the `scene` element. Can we not set it for an individual entity (I tried it didn't work). So in case we need different bounces for different entities are we to code them using the cannon.js integration as mentioned in the docs? Thanks

**Comment by donmccurdy** [comment]
Currently they are at the scene level. The way to expose them, I think, would be through a `physics-material` or `contact-material` component, as proposed in https://github.com/donmccurdy/aframe-physics-system/issues/54. But so far I haven't had the time to do that sorry.
