### ISSUE TITLE
how to programatically add entity with dynamic body?

### ISSUE THREAD

**Issue by imgntn** [donmccurdy/aframe-physics-system#12]
working on a bow and arrow and running into some issues trying to dynamically add the arrow to the scene and make it fly.

what's the proper way to make sure that the arrow's dynamic body is available to apply an impulse?

i get an ```entity.body is undefined``` error if i do it this way

```
    var matrixWorld = bow.object3D.matrixWorld;
    var shotDirection = new THREE.Vector3();
    shotDirection.setFromMatrixPosition(matrixWorld);

    var entity = document.createElement('a-entity');
    entity.className = "arrow"
    entity.setAttribute('obj-model', 'obj: #arrow-obj; mtl: #arrow-mtl')
    entity.setAttribute('scale', '0.05 0.05 0.05 ');
    entity.setAttribute('dynamic-body', 'shape:auto');
    scene.appendChild(entity);

    entity.addEventListener('loaded', function() {
      var shotPosition = entity.getAttribute('position');
      entity.body.applyImpulse(
        /* impulse */
        new CANNON.Vec3.copy(shotDirection),
        /* world position */
        new CANNON.Vec3().copy(shotPosition)
      );

    });
```

is there another technique i should be using?  a pool or something? 

thanks!!

**Comment by wmurphyrd** [comment]
The body creation isn't synchronous with the entity initialization, so the `loaded` event usually fires before the body is ready. Try listening instead for `body-loaded`, it's an [undocumented event](https://github.com/donmccurdy/aframe-physics-system/blob/7159b5ef4ae148eb58d6e0e9a0cebe362b172145/src/components/body/body.js#L85) that the entity will emit when `body` is ready

**Comment by donmccurdy** [comment]
The `body-loaded` event is a good way to handle this, yes. I've filed #13 to document events.

[Here's an example scene](https://github.com/donmccurdy/aframe-extras/blob/master/examples/force-push/index.html) where I'm dynamically adding or re-positioning dynamic bodies.

**Comment by imgntn** [comment]
great, the ```body-loaded``` event is working for me.  appreciate the help, friends.

**Comment by cityguy** [comment]
hey i'm adding dynamic-body on a sphere from script on runtime, but its not working, i'm using Aframe in 8thwall for AR.
Aframe v1.1.0
I tried adding entity.addEventListener('body-loaded', () => {}). 
but this also didn't work. 
All i'm doing is creating a sphere on runtime and adding dynamic-body on it and applying impulse force.
please help.
https://codepen.io/donmccurdy/pen/eRavEv  - Same as this example here.
