### ISSUE TITLE
Is it possible to make the user (camera) a body as well?

### ISSUE THREAD

**Issue by JerryWaaaaaaaa** [donmccurdy/aframe-physics-system#120]
Hi, I'm currently working on a 3D puzzle using the physics system. I want to let the user be able to climb the stairs and be blocked by the walls. Is there a way to make the camera a body as well so that the user can move around in the world and interact with the objects inside? Basically, I would like to achieve the following effect: http://schteppe.github.io/cannon.js/examples/threejs_voxel_fps.html

**Comment by donmccurdy** [comment]
It's possible yes — the `kinematic-body` component in aframe extras (https://github.com/donmccurdy/aframe-extras/) implements this. However, I would strongly recommend trying a navmesh-based approach first. See https://www.donmccurdy.com/2017/08/20/creating-a-nav-mesh-for-a-webvr-scene/. Using physics to control the camera hasn't worked particularly well in my experience (at least with CannonJS...), and causes problems in VR experiences. I'm trying to focus my time on VR-related stuff, so at this point I am not maintaining `kinematic-body`.
