### ISSUE TITLE
aframe physics gltf model model does not get parsed

### ISSUE THREAD

**Issue by nirajupadhyay11** [donmccurdy/aframe-physics-system#122]
I have found that, for some gltf models, the aframe-physics-system component fails to parse the model to create a wireframe around it even though the model is set as

dynamic-body=""shape: box"

For example: this model from sketchfab https://sketchfab.com/models/183df4dd59ea433cb7ebaf824ca8a0e1

You can download this model and try it.

I would like to understand what causes this and what can I change in the model so that the physics system parses the model correctly and a wire frame gets created. I am using v3.3.0 of Don Mccurdy's aframe-physics-system component.

**Comment by donmccurdy** [comment]
Could you create a demo?

**Comment by nirajupadhyay11** [comment]
Issue was with the model and not the physics parser.
