### ISSUE TITLE
How to set bullet speed?

### ISSUE THREAD

**Issue by arpu** [donmccurdy/aframe-physics-system#124]
building a simple bullet fire 

looks like  the hearts are falling down on the spawn point 

https://melodic-salamander.glitch.me/

**Comment by donmccurdy** [comment]
What are you doing to set the speed now? Initial velocity is probably what you want, e.g. `el.setAttribute('velocity', {x: 0, y: 0, z: -1})`. I wouldn't recommend physics for any sort of fast-paced shooter – collision detection will often miss collisions involving small, fast objects. See https://github.com/schteppe/cannon.js/issues/202. A raycaster is a better way to handle those cases.

**Comment by kfarr** [comment]
Related question while you're on the topic, any difference in this syntax vs. the one you presented?
`document.querySelector("#object").body.velocity.set(0, 0, -12);`
vs
`document.querySelector("#object").setAttribute('velocity', {x: 0, y: 0, z: -12})`

**Comment by arpu** [comment]
@donmccurdy  thx for pointing  me to this velocity inital values, this works fine now for me!

i had in mind to use CCD from https://github.com/schteppe/cannon.js/issues/366  in the long run

**Comment by donmccurdy** [comment]
@kfarr yeah, good point. The `velocity` component is applied on top of any velocity on the body. For a dynamic body it's probably better to do what you suggest. For a static body the component is helpful.
