### ISSUE TITLE
aframe-physics broken in aframe 0.9.0

### ISSUE THREAD

**Issue by nirajupadhyay11** [donmccurdy/aframe-physics-system#127]
I upgraded to aframe 0.9.0 with aframe-physics-system v3.3.0 and applyImpulse seems to be broken after that. I upgraded from aframe 0.8.2 and aframe-physics-system 3.3.0 where all was working fine.

Here is my code -
`entity.setAttribute('dynamic-body', true); 
entity.addEventListener('body-loaded', function () { 
 setTimeout(function () { 
     let pStart = new CANNON.Vec3(); 
     let force = pStart.copy(attachment.object3D.getWorldPosition()); 
     force.scale(140, force); 
     entity.body.applyImpulse(force, entity.body.position);
 }, 0); 
})
`
It used to work perfectly fine in aframe 0.8.2 but now I see this message in console log -

![image](https://user-images.githubusercontent.com/26413069/55270916-107d5a00-52cb-11e9-947e-2eef94d94e93.png)

**Comment by donmccurdy** [comment]
I'm not sure how to reproduce this – the `stress.html` example uses `applyImpulse` and still seems to work in aframe 0.9.1, would you be able to share a running demo?

**Comment by nirajupadhyay11** [comment]
Here is a codepen - https://codepen.io/nirajupadhyay11/pen/wbyodL

A-frame version is currently 0.8.2 and everything works. But, if you go to HTML settings and change the version to 0.9.0, it stops displaying

**Comment by donmccurdy** [comment]
In the JS console there is a warning:

```
core:a-node:error Failure loading node:   Error: "Unknown geometry schema `undefined`"
```

I think this means that A-Frame 0.9.0 requires you to do `geometry="primitive: box"` instead of `geometry="box"`, or the box will not be created.
