### ISSUE TITLE
Toggling between static and dynamic body breaks collision bounding box

### ISSUE THREAD

**Issue by Zetaphor** [donmccurdy/aframe-physics-system#128]
```javascript
el.removeAttribute('static-body')
el.setAttribute('dynamic-body', '')
```

Change position or rotation
```javascript
el.removeAttribute('dynamic-body')
el.setAttribute('static-body', '')
```
Collision bounding box and wireframe are now completely wrong

**Comment by InfiniteLee** [comment]
The correct way to do this is not to use the "helper" components and use the `body` component directly. Then you can use `el.setAttribute('body', {type: "static"})` or `el.setAttribute('body', {type: "dynamic"})` instead of removing then re-adding the components to toggle between the two modes.
