### ISSUE TITLE
Ammo: System keeps firing collisionend events

### ISSUE THREAD

**Issue by Zweidrittelstein** [donmccurdy/aframe-physics-system#134]
Upon further experimenting with ammo, I came across this bug:

After two entities have collided for the first time, the system just keeps emiting the 'collideend' event a couple times per second, even while they are still colliding. 

Short example (Use arrow keys to move orange ball):
https://glitch.com/edit/#!/tidy-cyclone

Side note: This only happens, if the emitting entity is dynamic, or kinematic - it works fine, if the emitting entity is static.

**Comment by donmccurdy** [comment]
In progress: https://github.com/donmccurdy/aframe-physics-system/pull/135.
