### ISSUE TITLE
object disappears to infinity when dynamic-body enabled

### ISSUE THREAD

**Issue by riebling** [donmccurdy/aframe-physics-system#138]
I am probably doing something wrong, but here's what happens: You have an object already in the scene. Then programmatically you turn on dynamic-body with setAttribute(). The behavior I'm observing is the object disappears, and if you find it in the editor has one of it's X, Y, or Z coordinates set to infinity/NaN.

There's probably some synchronization and other function calls needed to allow this to work better, to support building a scene where you can programmatically enable/disable physics. I've tried setting dynamic-body ahead of time, with "type: static" then switching it, same behavior results.

**Comment by ventoline** [comment]
I have the same issue

**Comment by donmccurdy** [comment]
Could you share a demo?

**Comment by riebling** [comment]
FWIW I can no longer reproduce this issue. I think it had to do with _when_ I was turning on the dynamic-body as 'dynamic' attribute. Just stumbled across this, and feel it could be closed now
