### ISSUE TITLE
Ammo:  Remove entity or attribute of Ammo-body will prevent collision detection.

### ISSUE THREAD

**Issue by gaegaelab** [donmccurdy/aframe-physics-system#141]
When I remove ammo-body,  "collidestart" and "collideend" no longer occur in the entire scene.
I removed it by the following way.

- Delete Entity with removeChild.
- Remove the ammo-body attribute with removeAttribute.

This bug will almost certainly occur with just one removing, but may not occur until it is removed with about three times.

Is there any solution?

### info
Hardware : Oculus Quest
Browser : Firefox Reality
import:
  https://mixedreality.mozilla.org/ammo.js/builds/ammo.wasm.js
  https://aframe.io/releases/1.0.3/aframe.min.js
  https://cdn.jsdelivr.net/gh/donmccurdy/aframe-physics-system@v4.0.1/dist/aframe-physics-system.min.js

**Comment by donmccurdy** [comment]
Merging with https://github.com/donmccurdy/aframe-physics-system/issues/137.
