### ISSUE TITLE
use cannon-es maintained cannonjs fork

### ISSUE THREAD

**Issue by arpu** [donmccurdy/aframe-physics-system#143]
cannon-es is maintained again 
would be nice to use this 

https://github.com/react-spring/cannon-es

https://discourse.threejs.org/t/cannon-js-the-physics-library-is-maintained-again/13519

**Comment by donmccurdy** [comment]
Looks promising to me! Unfortunately I don't think I will work on this myself any time soon; PRs welcome. It would probably also be necessary to migrate https://github.com/donmccurdy/three-to-cannon.

**Comment by arpu** [comment]
working on it

**Comment by arpu** [comment]
https://github.com/donmccurdy/aframe-physics-system/pull/147
