### ISSUE TITLE
Physics breaks with nested a-entities and rotations

### ISSUE THREAD

**Issue by kennardconsulting** [donmccurdy/aframe-physics-system#18]
The physics system seems to break (everything appears in the wrong place) if placed inside a parent a-entity that has a translation/rotation. For example:

	<a-scene physics>
		<a-entity position="3 0 0">
			<a-plane color="green" static-body height="3" width="3" rotation="-90 0 0" position="0 0 -5"></a-plane>
			<a-box color="red" dynamic-body position="0 5 -5"></a-box>
		</a-entity>
	</a-scene>

Here you will see the red box will fall and miss the green floor completely. But if you change the parent a-entity position to "0 0 0" then it lands as expected.

At a guess, this may be a similar problem to one I lodged a PR request against for sphere-collider: https://github.com/donmccurdy/aframe-extras/pull/124/commits/6f5627edaa9512ee24be5030e83bb1ee8f0544f5 (basically you are calling getWorldPosition for one set of co-ordinates but not the other)

It's fine if the rotation exists but is "0 0 0", so it's not the nesting per se that upsets it.

**Comment by wmurphyrd** [comment]
@donmccurdy I think I figured out the nested rotation fix

[body.js#L281](https://github.com/donmccurdy/aframe-physics-system/blob/master/src/components/body/body.js#L281)

Change 

`q1.multiply(q2.inverse());`

to

`q1.premultiply(q2.inverse());`

**Comment by donmccurdy** [comment]
Thanks! Will take a look at this soon.

**Comment by nirajupadhyay11** [comment]
Hello Don, any chance of this change being incorporated anytime soon? I have a gltf model, which when rotated with static body set as box, fails to cover the model.

**Comment by donmccurdy** [comment]
Could someone open a PR, if this seems to solve the issue?

**Comment by wmurphyrd** [comment]
I'll do it
