### ISSUE TITLE
static-body components do not collide with each other

### ISSUE THREAD

**Issue by kennardconsulting** [donmccurdy/aframe-physics-system#20]
It's not clear from the documentation, but `static-body` components do not appear to collide with each other?

In this example you can use WASD to move the green box. The blue box never registers 'collide'. Is this by design? If so, is there a way to use the (very useful) collision system outside of `dynamic-body`?

	<html>
	<head>
		<script src="dist/aframe-v0.4.0.js"></script>
		<script src="dist/aframe-physics-system.js"></script>

		<script>
			AFRAME.registerComponent('detect-collision', {

			  init: function ( t ) {

				this.el.addEventListener( 'collide', function ( e ) {
					console.log( 'collision' );
				} );
			  }
			} );
		</script>
	</head>
	<body>
		<a-scene physics="debug: true">

			<a-entity camera></a-entity>
			<a-box static-body color="green" position="-2 0 -3" wasd-controls reset-on-collision></a-box>
			<a-box static-body color="blue" position="0 0 -3" detect-collision></a-box>

		</a-scene>
	</body>
	</html>

**Comment by wmurphyrd** [comment]
You can harness the collisions from the physics system very efficiently, check out my `physics-collider` and `physics-collision-filter` components in PR #14.

You're right that static bodies don't collide, nor do sleeping bodies collide with static bodies or each other. [The logic is here in the physics broadphase](https://github.com/donmccurdy/cannon.js/blob/v0.6.2-dev1/src/collision/Broadphase.js#L55-L70)

**Comment by donmccurdy** [comment]
That's correct: `static-body` components do not collide with one another. There's a bit more documentation on it [here](https://github.com/donmccurdy/aframe-physics-system#components--dynamic-body-and-static-body). It's baked into cannon.js (and probably improves performance a lot) so unfortunately nothing I can do about it at the moment. 

For simpler cases, I am using `aabb-collider` (from A-Frame core) `sphere-collider` (from aframe-extras), which of course are exempt from all this.

**Comment by donmccurdy** [comment]
You can also hack a custom `foo-body` component to behave like you're describing. That's what I intended to do with [`kinematic-body`](https://github.com/donmccurdy/aframe-extras/blob/master/src/misc/kinematic-body.js). It gets really ugly really fast, though. I probably won't maintain that too much longer.

**Comment by donmccurdy** [comment]
Oh and feel free to add your own CANNON.Body to the scene, in a custom component. It's just `sceneEl.systems.physics.addBody(body)`. Then you can do whatever you want, if cannon.js supports it. :)
