### ISSUE TITLE
Example is broken (Type errors) in A-Frame 0.5.0

### ISSUE THREAD

**Issue by i3games** [donmccurdy/aframe-physics-system#23]
The example does not work in in A-Frame 0.5.0 - both current Firefox and Chrome (Mac) throw TypeError.

Chrome: 
```
Uncaught TypeError: Cannot read property 'position' of undefined
    at i.<anonymous> ((index):51)
```

Firefox: 

`TypeError: box.body is undefined[Learn More] examples:51:1`

**Comment by donmccurdy** [comment]
Looks good for me after @wmurphyrd's update.

**Comment by i3games** [comment]
Not fixed, same errors in  the current main branch.

**Comment by donmccurdy** [comment]
@i3games could you add details or provide a demo? I just cloned a new copy of this repo and ran `npm i && npm run dev` and the example works as expected.

**Comment by i3games** [comment]
Yeah, works fine. Looks like I had some bug in my setup. Thanks for investigating.
