### ISSUE TITLE
dynamic-body fails on custom object (.obj)

### ISSUE THREAD

**Issue by banada** [donmccurdy/aframe-physics-system#31]
Hi, I've been trying to fix this myself but no luck.

When I include this:
`<a-entity hoverable grabbable stretchable drag-droppable obj-model="obj: #my-obj; mtl: #my-mtl" scale="1 1 1" position="1 3 -5" class="thing" dynamic-body="shape: box"></a-entity>`
My .obj model hangs in mid-air, with no bounding box.

If I use `shape: auto`, the object drops through the floor, which is:
`<a-plane static-body rotation="-90 0 0" width="30" height="30" color="grey"></a-plane>`

`hoverable grabbable stretchable drag-droppable` is from https://github.com/wmurphyrd/aframe-super-hands-component. I have physics debug on.

Thanks!

**Comment by donmccurdy** [comment]
It's normal that it drops through the floor with `shape:auto` (see #9), but not that `shape:box` doesn't work. Any errors in the JS console? And are you on the latest version of aframe-physics-system?

**Comment by banada** [comment]
Including the aframe-physics-system fixed my issue. I thought the latest version comes packaged with aframe-extras?

**Comment by donmccurdy** [comment]
Great! :) It does have the latest physics right now, assuming you're also on the latest aframe-extras. But their releases aren't always at the same time, so extras can be a little behind sometimes. I wouldn't include both aframe-extras and aframe-physics-system both in the project, though.

**Comment by banada** [comment]
Okay, thank you! I'll just take the parts I need from aframe-extras :)
