### ISSUE TITLE
Is it possible to nest entities without physics?

### ISSUE THREAD

**Issue by delapuente** [donmccurdy/aframe-physics-system#34]
I have this A-Frame scene graph:
```html
<a-box id="cardboard" dynamic-body="mass: 0.01" position="0 0.9 -0.60" geometry="width: 0.05; depth: 0.05; height: 0.003" color="#008000">
      <a-box id="chip" position="0 0.002 0.01" geometry="width: 0.02; depth: 0.02; height: 0.001" color="#000"></a-box>
</a-box>
```
I want the nested box to not have physics and keep its position relative to its parent. But as soon as I came up with this setup, running the simulation make collision body to be misplaced. What am I doing wrong?

![screenshot-eata - entrenador virtual-1496083743593](https://cloud.githubusercontent.com/assets/757942/26559498/549005ba-44b0-11e7-8b06-62a8db8c7300.png)

**Comment by donmccurdy** [comment]
I think this is more than the automatic shape detection can handle, having things nested inside one another. If you add the inner shape later, after the `body-loaded` event has fired, it shouldn't affect the shape of the physics body.

Or, you can set `dynamic-body="shape: none"` to prevent any shape from being created, and then create a shape yourself.

[Codepen Demo](https://codepen.io/donmccurdy/pen/BRXNzP/?editors=1010)

Snippet:

```html
<a-entity id="cardboard" dynamic=body="shape: none; mass: 0.01" ...></a-entity>
```

```js
var cardboardEl = document.querySelector('#cardboard');
cardboardEl.addEventListener('body-loaded', function () {
  var halfExtents = new CANNON.Vec3(0.5, 0.2, 0.5);
  cardboardEl.body.addShape(new CANNON.Box(halfExtents));
});
```

**Comment by delapuente** [comment]
I'll try. Thank you!
