### ISSUE TITLE
.obj elements not recognized

### ISSUE THREAD

**Issue by communicationbreakdown01** [donmccurdy/aframe-physics-system#35]
Using the static-body component does not work on .obj files. The debug mode shows no wireframe around the object. It works perfectly on simple geometries though. 

I am using the component like this:

`<a-entity obj-model="obj: url(./img/mini-house.obj)" static-body="shape:box" mtl="color:blue; side:double"></a-entity>`

**Comment by donmccurdy** [comment]
Hi @communicationbreakdown01, could you share your model or a Codepen? I'm not sure how to guess why it would work with some models but not yours, without more details. Thanks.

**Comment by sparksia** [comment]
I'm having the same issue, except for me only a section of the whole model gets a wireframe. Also, the wireframe moves off the object when I give the object a new parent. You can find the model I'm using here https://skfb.ly/6rYOZ :)
It shows the same section in a wireframe when I turn it into a dynamic-object, but the entire object still falls through my static floor as if even that section doesn't collide

**Comment by donmccurdy** [comment]
I have fixed what I assume was the issue, here: https://github.com/donmccurdy/three-to-cannon/commit/cba2f53d43e6526122b79724ee7f7764dbd8229c

Closing this issue, but would welcome example models and/or Codepen demos if there are further problems.
