### ISSUE TITLE
_wakeUpAfterNarrowphase' of undefined

### ISSUE THREAD

**Issue by darioodiaz** [donmccurdy/aframe-physics-system#36]
Hi ! I was playing and creating a simple shot game, when click I add via createElement a a-sphere child and applyImpulse when collision is detected I remove the bullet and the target (the other object) and have that error
`
Uncaught TypeError: Cannot read property '_wakeUpAfterNarrowphase' of undefined
    at World.internalStep (aframe-physics.min.js:7)
    at World.step (aframe-physics.min.js:7)
    at r.tick (aframe-physics.min.js:8)
    at aframe.min.js:250
    at Array.forEach (<anonymous>)
    at HTMLElement.value (aframe.min.js:250)
    at HTMLElement.value (aframe.min.js:250)
    at aframe.min.js:369
`

Am I doing something wrong? and other thing is that if add dynamic-body to a entity created via javascript 
(like createElement) the body propery doesnt exists so I use a 1s timeout hack to use the body property

**Comment by donmccurdy** [comment]
> Am I doing something wrong?

I have no idea. :) Could you create a Codepen showing the issue?

> and other thing is that if add dynamic-body to a entity created via javascript
(like createElement) the body propery doesnt exists so I use a 1s timeout hack to use the body property

The body might not be created immediately, especially if there is a 3D model involved. You can listen for it to be created, though:

```
el.addEventListener('body-loaded', function () {
  console.log(el.body);
});
```

**Comment by darioodiaz** [comment]
Thanks for that snippet, there is a link to the demo, just press the space bar and the error will raise when the balls touch each other. Thank you

**Comment by donmccurdy** [comment]
@darioodiaz missing the link 😉

**Comment by darioodiaz** [comment]
oh, sorry, my bad https://s3.amazonaws.com/dariodiazbucket/game.html

**Comment by donmccurdy** [comment]
Here's part of the issue:

```js
body.applyImpulse(new CANNON.Vec3(0, 0, -10), position);
                                              ^
```

`position` is an A-Frame vector, {x: ..., y: ..., z: ...}, and needs to be a CANNON.Vec3. You can fix this with:

```js
body.applyImpulse(new CANNON.Vec3(0, 0, -10), new CANNON.Vec3().copy(position));
```


The second part was a bit odd. I tracked down an answer here: http://www.html5gamedevs.com/topic/28819-solved-how-dispose-mesh-in-oncollideevent/. Basically, you can't remove a body immediately when the `collide` event fires, because the physics simulation hasn't finished that frame yet. Instead, use a setTimeout to remove the object between frames:

```js
shot.addEventListener('collide', function (e) {
    setTimeout(function() {
      if (e.detail.body.el.getAttribute('enemy')) {
          console.log('collision with enemy', e.detail.body.el);
          e.detail.target.el.parentNode.removeChild(e.detail.target.el);
          e.detail.body.el.parentNode.removeChild(e.detail.body.el);
      }
    }, 0);
});
```

**Comment by darioodiaz** [comment]
Thank you so much, I was thinking about that, because the collide detector should finish the iteration cycle but I wasn't sure about that, I'll test it

**Comment by darioodiaz** [comment]
the collision code works, but the body-loaded code (I implement like this)
`
shot.addEventListener('body-loaded', function () {
                    this.body.applyImpulse(new CANNON.Vec3(0, 0, -10), new CANNON.Vec3().copy(this.getAttribute('position')));
                });
                this.scene.appendChild(shot);
`
keep the ball rotating but not moving forward, any idea why? I close the issue beacuse the original issue was solved, but can you help me with this? Thank you so much :)

**Comment by donmccurdy** [comment]
> keep the ball rotating but not moving forward, any idea why?

I don't think I understand; can you provide a demo showing the issue?

**Comment by darioodiaz** [comment]
Sure, this is the link

https://s3.amazonaws.com/dariodiazbucket/game-issue.html

press the spacebar and you will see a white ball rotating but not moving, the camera has wasd-controls if you want to move aorund. Thanks :)

**Comment by donmccurdy** [comment]
Still looking into exactly why this is happening, but you can work around it in two ways:

```
shot.addEventListener('body-loaded', function() {
    setTimeout(function() {
        var body = shot.body;
        var pos = new CANNON.Vec3().copy(shot.getAttribute('position'));
        body.applyImpulse(new CANNON.Vec3(0, 0, -10), pos);
    }, 0);
});
```

```
shot.addEventListener('body-loaded', function() {
  var body = shot.body;
  var pos = new CANNON.Vec3().copy(shot.getAttribute('position'));
  body.applyForce(new CANNON.Vec3(0, 0, -1000), pos);
});
```

The first uses a `setTimeout` to ensure you're applying the impulse between frames. The second uses `applyForce` instead of `applyImpulse`, with a larger value, to keep applying movement over time.

**Comment by arthurmougin** [comment]
I fixed the issue by making the event callback function async, it removes the need for a weird setTimeout that messed up my context. does it fix it for you ?
