### ISSUE TITLE
Problem with convex hull creation

### ISSUE THREAD

**Issue by sparksia** [donmccurdy/aframe-physics-system#37]
Hello,
I'm trying to use a convex hull collider for my .obj model (which you can view [here](https://skfb.ly/6rYOZ)), but was running into issues with assigning the collider, where the wireframe would highlight only a small section of the whole model, and even that section would pass through my other objects (simple cubes with box colliders). So I then switched to a simpler [model ](https://skfb.ly/68AsK) to see if it worked. 
I load the .obj models (and .mtls if they have them) as a-asset-items, and then create a-entities as follows: `<a-entity id="hull" class="model" obj-model="obj: #hull" position="-0.5 1 1" collision-filter="group: red; collidesWith: default, red" stuck dynamic-body="shape: hull; linearDamping: 0.99; angularDamping: 0.99" material="color: red"></a-entity>`. However, for both the complex model and this simpler one, I get the error below. I even tried giving primitive cubes a hull collider and got this same error.
![capture](https://user-images.githubusercontent.com/24358364/27146484-27ba759a-5142-11e7-820b-42a4926c6b60.PNG)
Upon investigating the code in aframe-extras.js, it looks like the problem occurs when getGeometry() is called, where getGeometry calls getMeshes(), and the meshes that are pushed actually do not even have any vertices component. 
So then I thought maybe it's caused by the object not being loaded completely, so I tried adding an event listener for 'body-loaded' that would add the dynamic-body component afterwards. When I tried this, it looks like the object is given a dynamic-body with a box shape by default, and this doesn't get overridden by the "setAttribute" that I call later.
So I thought perhaps the problem could be in the way the .obj models are loaded on aframe, and decided to try using .dae models instead. However, that threw a different error, shown below:
![capture1](https://user-images.githubusercontent.com/24358364/27146485-290cccc2-5142-11e7-84fc-b211c7b87e5b.PNG)
This error keeps popping up in the console endlessly, with the number in the [brackets] incrementing each call.
I hope you can help me out with this :)
Thanks!

**Comment by donmccurdy** [comment]
Hi @sparksia — the uncaught errors are fixed here (https://github.com/donmccurdy/three-to-cannon/commit/cba2f53d43e6526122b79724ee7f7764dbd8229c). The results I get now are:

- complex OBJ freezes chrome when trying to compute hull
- simplified DAE works correctly, but the warnings about face normals continue.

I'm using a library (https://github.com/donmccurdy/three-to-cannon/blob/master/lib/THREE.quickhull.js) to compute the convex hull, and unfortunately fixing those remaining errors is more than I have time to do. If the warnings about face normals are a problem, I might suggest `shape:box` which of course is much simpler to simulate. I would also be interested in suggestions for more robust convex hull implementations. :)

**Comment by sparksia** [comment]
Yes, it works now! For the simple object, at least :)
The .obj hull doesn't seem to deal with collisions well and results in super shaky lag (on the vive), but the collada model seems to be doing well. One thing I noticed is that for the other colliders, like the box, sphere, etc. you can "grab" anywhere on the inside of the shape, and it responds. This doesn't happen for the hull though, and I suspect it's because the hull is modeled as a bunch of planes?

**Comment by donmccurdy** [comment]
Hm I see. Yeah, my laptop didn't even manage to compute the hull on the OBJ, it just froze. I think that model is just too complicated.

Also note that you can specify `shape: none` and then attach one (or more) shapes of your own. Using multiple spheres and boxes for a single body is the most efficient way to go (and probably closest to what game engines do), but I don't have an automatic way to generate those.

Can you not use the `grab` component with `shape:hull` at all, then?

**Comment by sparksia** [comment]
The grab does work with the `shape:hull`, but only on the surface of model. I'm trying to use raycasters to check for grab events that occur within the model to work around this :)
When you say attach other shapes to a model with `shape: none`, do you mean using lock constraints? This seems to work well for static bodies, but not so well with dynamic bodies. The object with the `shape: none` component doesn't follow the rotations of the object it's attached to (but translations work fine). And if I do give them both colliders, I run into a different issue ( #41 )

**Comment by donmccurdy** [comment]
@sparksia not lock constraints, no — you can do this:

```html
<a-entity id="thing" dynamic-body="shape: none"></a-entity>
```

```js
var el = document.querySelector('#thing');
var shape = new Sphere(1.5);
thing.body.addShape(shape);
```

You can also specify a position and rotation of the shape, and add multiple shapes (e.g. boxes) to approximate your model. See the cannonjs docs for more: http://schteppe.github.io/cannon.js/docs/classes/Body.html

As far as why the hull would only get collisions at the surface of the model, unfortunately I don't know but that sounds like a limitation of the physics library.

**Comment by sparksia** [comment]
Oh, I see! That looks good, thanks :)
