### ISSUE TITLE
Constraints error when touching target

### ISSUE THREAD

**Issue by sparksia** [donmccurdy/aframe-physics-system#41]
Hello,
I'm trying to use a basic lock constraint between two objects, where object "blue" references object "red" as follows:
`<a-entity class="model" id="red" mixin="cube" material="color: red" position="0 1 -1" collision-filter="group: red; collidesWith: default, red"></a-entity>`
`<a-entity class="model" id="blue" mixin="cube" material="color: blue" position="0 1.6 -1" collision-filter="group: red; collidesWith: default, red" constraint="target: #red"></a-entity>`
The basic function of this constraint work all right; when I pick up and move the red cube, the blue one follows. However, if my controller's collider even slightly touches the blue box, this error is thrown and the program crashes.
![19357687_10212764969181164_944718763_n](https://user-images.githubusercontent.com/24358364/27259875-d24bdaea-5425-11e7-84ce-3312bd448965.png)
I hope you could take a look at this.
Thanks!

Edit: Also, placing a collada model as the target of a constraint doesn't seem to work. My two entities are defined as:
`    <a-entity id="hulldae" class="model" collada-model="#hulldae" position="1 1 1" collision-filter="group: red; collidesWith: default, red" stuck dynamic-body="shape: box; linearDamping: 0.99; angularDamping: 0.99"></a-entity>`
`<a-entity id="mol" class="model" obj-model="obj: #model1; mtl: #mat1" position= "-0.5 1 1" collision-filter="group: red; collidesWith: default, red" dynamic-body="shape: box; linearDamping: 0.99; angularDamping: 0.99" constraint="target: #hulldae"></a-entity>`
However, if I place the `constraint="target: #hulldae"` on the `#mol`, there is no constraint action, whereas if I place `constraint="target: #mol` on the `#hulldae`, they move together as expected.

Links to the models: 
hulldae: https://skfb.ly/68AsK
mol: https://skfb.ly/6rYOZ

The error remains if I turn both into collada objects; it only seems to lock correctly for .obj ones. I do want to use collada objects though, as .obj collisions aren't as good. 

Thanks! :)

**Comment by donmccurdy** [comment]
Given that the error happens on collision, I'm curious what this `collision-filter` component is. And, have you tried using `<a-scene physics="debug: true"> ...`? This adds red outlines around the physics body of an object, so you can tell whether the bounding box was computed correctly.

If you could provide a Codepen or JSFiddle demonstrating the issue that would also help here, thanks.

**Comment by wmurphyrd** [comment]
`collision-filter` must by my prototype from #14 ([direct link](https://github.com/donmccurdy/aframe-physics-system/pull/14/files#diff-7339369245e7d2bd39d0d78c4d13f9f8)). I haven't tested it with any recent versions of the physics system, so it could have issues (although it is pretty simple). Now that I've finished a major rewrite of `super-hands`, I was thinking of spinning off the components in #14 to their own package to finish and polish them (although I'd be happy to merge it back in to this repo at some point)

**Comment by sparksia** [comment]
Yes, collision-filter was from #14. I did use "debug: true", and it looks like the bounding box is computed correctly. I'm not sure what's changed, but I'm not getting the error anymore - I'll provide a codepen if I come across it again. Thanks!
