### ISSUE TITLE
Attraction to origin forces

### ISSUE THREAD

**Issue by fabiodr** [donmccurdy/aframe-physics-system#44]
Do you have some clue how can i apply forces to reproduce this effect of bigger attraction when an object is far from origin position and slow down when arriving at origin?

https://youtu.be/RLEEVGxu_k8?t=3m16s

And if physics is the best approach to this (as it can collide things on the path) or may be handled with animation?

Thanks in advance

**Comment by donmccurdy** [comment]
If you don't necessarily need the object to collide with other things (just simple click-to-drag using controllers) then personally I would avoid the physics engine — write a small component that tracks current velocity while the object is being moved by the player, and then applies that velocity on every `tick()` after that, tweaking the velocity slightly toward the origin each time.

If you do need the collisions you'll want physics, and in that case I'd suggest using a point-to-point constraint with weak `maxForce`:

```html
      <!-- A gray static-body -->
      <a-box id="static-box"
             color="#777"
             position="-0.5 0.5 0.0"
             static-body>
      </a-box>
      <!-- A red dynamic-body constrained to hang from the static box -->
      <a-box color="#F00"
             position="0.5 -0.5 0.0"
             dynamic-body
             constraint="type: pointToPoint;
                         maxForce: 100;
                         target: #static-box;
                         pivot: -0.5 -0.5 0.5;
                         targetPivot: 0.5 -0.5 0.5">
      </a-box>
```

^ assuming that works reasonably well, there are some tricks to get the static body out of the picture. May also want to turn off gravity.
