### ISSUE TITLE
Kinematic Body?

### ISSUE THREAD

**Issue by jlieb10** [donmccurdy/aframe-physics-system#47]
Was trying to figure out how to get the player camera to act as a rigid body but ended up having to use `aframe-extras` lib for this as it doesn't seem like this was ported over to the new physics system. Please let me know if I missed something.

**Comment by donmccurdy** [comment]
That's correct: aframe-extras includes all of aframe-physics-system, and adds `kinematic-body` as well. `kinematic-body` only works with the controls from aframe-extras, and is not really workable in roomscale VR, so i've left it out of the standalone physics system here.

**Comment by jlieb10** [comment]
@donmccurdy rad, thanks for the info!
