### ISSUE TITLE
Constrained objects and collision

### ISSUE THREAD

**Issue by evhan55** [donmccurdy/aframe-physics-system#48]
Hi,

I have two objects that I constrain to each other with a `lock` constraint, but they constantly collide and spin out of control once connected, even if `collideConnected` is set to `false` on both.

Am I using constrains incorrectly?

**Comment by donmccurdy** [comment]
My mistake — this should be fixed on the next version.

**Comment by donmccurdy** [comment]
Also `collideConnected` should be on the constraint not the body, so should only need to use it once.

**Comment by evhan55** [comment]
Oh awesome!
It works!  I added a 'gluing' feature to my app, now seems to do what I was expecting!
Thanks so much!
![glueing](https://user-images.githubusercontent.com/699840/28759707-693a6e30-756e-11e7-9e55-052dfc378d12.gif)

**Comment by donmccurdy** [comment]
NICE that looks great! 😄
