### ISSUE TITLE
Support Cannon compound shapes

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/aframe-physics-system#53]
See discussion on https://github.com/donmccurdy/aframe-extras/issues/44.

**Comment by wmurphyrd** [comment]
Here's one take: use the existing body API to define the child body shapes, then merge them after bodies have loaded.

Source: https://github.com/wmurphyrd/aframe-physics-extras/blob/master/src/body-merger.js

Live Example: https://wmurphyrd.github.io/aframe-physics-extras/examples/body_merger/

Example source: https://github.com/wmurphyrd/aframe-physics-extras/blob/master/examples/body_merger/index.html

**Comment by donmccurdy** [comment]
https://github.com/donmccurdy/aframe-physics-system/pull/90
