### ISSUE TITLE
collide event seems to be not firing

### ISSUE THREAD

**Issue by gftruj** [donmccurdy/aframe-physics-system#57]
Hi, I'm trying to listen for the `collide` event, 
simply by `entityWithADynamicBody.addEventListener('collide',(e)=>{});`

It seems to be correct, moreover it works on earlier versions (1.4.1 at least), as presented in my [fiddle](https://jsfiddle.net/782ggtwx/1/).

But when i link the newest version ([2.0.0](<script src="//cdn.rawgit.com/donmccurdy/aframe-physics-system/v2.0.0/dist/aframe-physics-system.min.js"></script>)), it doesn't fire at all, as presented in my [fiddle](https://jsfiddle.net/782ggtwx/2/).

Am I missing something here ?
a-frame version: 0.6.1.

**Comment by donmccurdy** [comment]
It is a bug, thanks! I'm merging this issue with https://github.com/donmccurdy/aframe-physics-system/issues/58 and will track a fix there. :)

**Comment by enquel** [comment]
Is this fixed? Seems I have the same issue

**Comment by donmccurdy** [comment]
@enquel it is fixed in aframe-physics-system v2.1.0+. If you're loading the physics system from aframe-extras, then it is still on an older version. Also note that this only works with local physics (`physics="driver: local"`) and not when running physics on a web worker: https://github.com/donmccurdy/aframe-physics-system/issues/58#issuecomment-328712527

**Comment by donmccurdy** [comment]
Yeah, it doesn't work to include both together (aframe-extras has physics built in already) so there's probably no workaround right now. I think this will be fixed with v4 of aframe-extras in January.

**Comment by enquel** [comment]
Thanks! Will it work if I use just checkpoint controls from extras along with the physics system?

**Comment by donmccurdy** [comment]
No sorry, I don't think it will work yet.

**Comment by enquel** [comment]
Ok thanks a lot anyway, you saved me much time on makeshift hacking ;) Great job with the entire system by the way!

**Comment by donmccurdy** [comment]
Thanks 🙂 Keep an eye on the aframe-extras v4 milestone [here](https://github.com/donmccurdy/aframe-extras/milestone/2) to know when the fix will be released.
