### ISSUE TITLE
Version 2.0.0 does not fire collision events

### ISSUE THREAD

**Issue by AVGP** [donmccurdy/aframe-physics-system#58]
Given the following code:

```html
<a-scene physics="debug: true">
  <a-box id="box" dynamic-body="" position="0 10 0" color="red"></a-box>
  <a-box id="world" static-body position="0 0 0" scale="9.5 0.2 9.5" rotation="0 0 0" color="cyan"></a-box>
</a-scene>

<script>
document.getElementById('box').addEventListener('collide', function() {
  console.log('collided!')
})
</script>
```

This is firing the `collide` events just fine when using v1.4.3 but doesn't fire anything in 2.0.0.

I wonder if this is a desired change (in which case the docs need an update) or a regression

**Comment by donmccurdy** [comment]
Copied @gftruj's report in #57 —

***

Hi, I'm trying to listen for the `collide` event, 
simply by `entityWithADynamicBody.addEventListener('collide',(e)=>{});`

It seems to be correct, moreover it works on earlier versions (1.4.1 at least), as presented in my [fiddle](https://jsfiddle.net/782ggtwx/1/).

But when i link the newest version ([2.0.0](<script src="//cdn.rawgit.com/donmccurdy/aframe-physics-system/v2.0.0/dist/aframe-physics-system.min.js"></script>)), it doesn't fire at all, as presented in my [fiddle](https://jsfiddle.net/782ggtwx/2/).

Am I missing something here ?
a-frame version: 0.6.1.

**Comment by donmccurdy** [comment]
Yep thanks! It is a regression with the new version. We'll need to set things up a bit differently to support these events coming from a worker, but it shouldn't be too much work to fix.

**Comment by nbabanov** [comment]
Guys could you give an estimate about when is it supposed to be fixed? :)

**Comment by AVGP** [comment]
I hope to work on it this week

Am 04.09.2017 9:52 vorm. schrieb "Nikolay Babanov" <notifications@github.com

**Comment by donmccurdy** [comment]
To get this unblocked I went ahead and fixed the `collide` events for the default mode (`physics="driver: local"`). The event is still not working when running physics in a Web Worker; that will a little work to get right.
