### ISSUE TITLE
don't set `el.body`

### ISSUE THREAD

**Issue by ngokevin** [donmccurdy/aframe-physics-system#59]
This is a DOM expando property which creates a circular reference:

`el.body.el`

Which itself has circular references:

`el.body.el.object3D.el`

I think if this element has to be cleaned up, it creates work for the cycle collector.

**Comment by donmccurdy** [comment]
Should it resolve things if, instead, I don't set `body.el`? I think `el.body` is the more useful of the two.

**Comment by ngokevin** [comment]
Could also make it a function. `el.getPhysicsBody()`. Maybe unsetting `body.el` will help, but Cannon could potentially have circular references. There's little out there about the cycle collector though. Don't think it's too big a deal.

**Comment by wmurphyrd** [comment]
I use `body.el` in [`physics-collider`](https://github.com/wmurphyrd/aframe-physics-system/blob/interfaces/src/components/interfaces/aframe-physics-collider.js#L35) (and I just looked back at the source and realized it does not depend on the `'collide'` event, so finishing that component up could be a solution to #58).

However, I could live without `body.el` if the driver stored a map and kept it updated via `addBody`/`removeBody`

lmk if you're interested in seeing this in a PR

**Comment by ngokevin** [comment]
hmm, probably not a big deal unless i can measure it's a perf problem.
