### ISSUE TITLE
Physics not active on new components

### ISSUE THREAD

**Issue by thenayr** [donmccurdy/aframe-physics-system#6]
I'm surely doing something wrong here, but here is a super basic example of what I'm trying to do (real implementation is in aframe-react).

```
# html snippet
<a-scene id="myscene" physics="debug: true">

</a-scene>
```

From console in browser:

```
var box = document.createElement('a-box')
box.setAttribute('dynamic-body', '');
document.getElementById('myscene').appendChild(box)
```

The box is appended with the proper `dynamic-body` attribute, but it acts as though it is a normal entity with no physics attached.

Do I need to create a custom component in order for this to work properly?

**Comment by donmccurdy** [comment]
Hi @thenayr — your code looks OK to me. [Here's a similar example](https://github.com/donmccurdy/aframe-extras/blob/master/examples/platforms/index.html) of my own, which does work. A common issue is getting the order of scripts right. Generally, you'll need:

```html
<head>
  ...
  <!-- aframe.js -->
  <!-- aframe-physics-system.js and any other scripts registering components -->
</head>
<body>
...
<a-scene> ... </a-scene>
<script>
document.querySelector('a-scene').addEventListener('render-target-loaded', function () {
  // any code that appends things to the scene
});
</script>
</body>
```

Code that appends to the scene can also live be put inside a component (in which case it should be included _before_ the scene, as shown [here](https://github.com/donmccurdy/aframe-extras/blob/master/examples/force-push/index.html).

**Comment by thenayr** [comment]
Thanks.

Looks like the key here was no setting the attribute `dynamic-body` prior to appending the element:

```
# Doesn't work
var box = document.createElement('a-box')
box.setAttribute('dynamic-body', '');
document.getElementById('myscene').appendChild(box)
```

```
# Does work
var box = document.createElement('a-box')
document.getElementById('myscene').appendChild(box)
box.setAttribute('dynamic-body', '');
```

Here is my React implementation (full disclosure, this code is probably gross):

```
import React from 'react';
import ReactDom from 'react-dom';
import {Entity} from 'aframe-react';

class Pod extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            name: props.name,
            color: props.color
        }
    }

    componentDidMount() {
        ReactDom.findDOMNode(this).setAttribute('dynamic-body', '');
    }

    render() {
        return(
            <Entity 
            id={`${this.state.name}`}
            key={`${this.state.name}`}
            geometry={{ primitive: 'box' }} 
            shape="box" 
            material={`color: ${this.state.color}; metalness:0.7`} >
                <Entity light={{type: 'point', color: '#63C7B2', intensity: '0.2'}} position="0 0 0" />
            </Entity>
        )
    }
}
 
export default Pod;
```

**Comment by jesstelford** [comment]
Possibly related to: https://github.com/ngokevin/aframe-react/pull/43

**Comment by donmccurdy** [comment]
Not sure about react (some separate issues opened about that) but AFAIK physics is working ok with new entities now.
