### ISSUE TITLE
Physics materials and contact materials not applied in v2.

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/aframe-physics-system#63]
1. [System creates a default material and contact material](https://github.com/donmccurdy/aframe-physics-system/blob/master/src/system.js#L86-L94).
2. [Body attempts to reference default material, but gets undefined](https://github.com/donmccurdy/aframe-physics-system/blob/master/src/components/body/body.js#L42).
3. [Local driver looks like it should use materials correctly](https://github.com/donmccurdy/aframe-physics-system/blob/master/src/drivers/local-driver.js#L72-L87), probably haven't tested that path on WW.

**Comment by machenmusik** [comment]
On the second point
> material: this.system.material,
There is no system.material, right?
Only this.system.driver.materials[] ...

**Comment by donmccurdy** [comment]
Correct, I think that's a bug from the refactoring earlier.
