### ISSUE TITLE
Dynamic body falls of static ground

### ISSUE THREAD

**Issue by Jonas-Arvidsson** [donmccurdy/aframe-physics-system#64]
I'm actually having a bunch of issues with what I'm trying to do, but I think I'll solve most of them if I can get this one thing to work.

I have an entity that I want to control with the WASD keys and I want it to be able to collide with other objects, both static and dynamic. The problem with this is that if I set my entity as a dynamic body, it falls through the ground! I believe it has to do with my implementation of the camera I have connected to the entity, as my other entities with dynamic bodies stay in place as they should. 

Here is my entity 

       <a-entity collision-detect static-body id="rover" gltf-model="#marsRover" movement-controls 
          scale="0.005 0.005 0.005">
            <a-entity scale="200 200 200" rotation="0 180 0" position="0 150 50">
                <a-entity camera look-controls></a-entity>
            </a-entity>
       </a-entity>

and my ground

        <a-entity id="plane" static-body geometry="primitive: plane; height: 20; width: 20" material="color: 
             grey" rotation="-90 0 0"> </a-entity>

Can I also ask if it's possible to disable dynamic bodies from moving and bouncing around after a collision (i.e make them stand still)?

**Comment by donmccurdy** [comment]
> Can I also ask if it's possible to disable dynamic bodies from moving and bouncing around after a collision (i.e make them stand still)?

Normally you can create "physics materials" that determine how things bounce. E.g., causing them to not slow down when they collide, or to stop entirely. This is broken in v2, tracking here: https://github.com/donmccurdy/aframe-physics-system/issues/63

> The problem with this is that if I set my entity as a dynamic body, it falls through the ground!

This is related to https://github.com/donmccurdy/aframe-physics-system/issues/9. There are several suggestions there, but tl;dr it is not currently possible to turn a custom model into the terrain for your physics simulation, without digging into CannonJS and doing a fair bit of custom setup. You probably want to start with a flat plane as the ground, and get everything working that way first.

I'd suggest adding comments on #9 if you have questions about this, to keep that discussion in one place.

**Comment by wmurphyrd** [comment]
@Jonas-Arvidsson another option for making things settle down is to use [damping and/or sleep settings on the physics body](http://schteppe.github.io/cannon.js/docs/classes/Body.html).

[Here's a draft component to make entities come to rest after a collision](https://github.com/donmccurdy/aframe-physics-system/pull/14/commits/5a5f6f6d7cd1b4c4b37f6f1d3e612e646b67ab46#diff-dcdbbebd25590a8dc903621ec3e0d515).
