### ISSUE TITLE
the 'collide' event can't be detected as expected when applying the following code. 

### ISSUE THREAD

**Issue by yuicer** [donmccurdy/aframe-physics-system#68]
```
var playerEl = document.querySelector('[camera]');
playerEl.addEventListener('collide', function (e) {
  console.log('Player has collided with body #' + e.detail.body.id);

  e.detail.target.el;  // Original entity (playerEl).
  e.detail.body.el;    // Other entity, which playerEl touched.
  e.detail.contact;    // Stats about the collision (CANNON.ContactEquation).
  e.detail.contact.ni; // Normal (direction) of the collision (CANNON.Vec3).
});
```
enviroment: aframe 0.7
`playerEl.addEventListener('collide', function (e) {}` it doesn't work

**Comment by donmccurdy** [comment]
Could you include more information (ideally a demo) about what you're trying to do? This example code assumes you have a `*-body` component attached to the camera — collisions are only between things set up for physics.

**Comment by yuicer** [comment]
i'm sorry there is no demo currently, i will try to get it done later.
the code 
```
<a-camera id="camera" wasd-controls="fly:true">
    <a-box id="box1" static-body position="5 1.5 -5" width="1" height="1" depth="1"></a-box>
</a-camera>
<a-box id="box2" dynamic-body position="5 -1.5 -5" width="1" height="1" depth="1"></a-box>
```
when the camera-box1 hit the box2 ,it does make box2 moved, but nothing print out .
```
var playerEl = document.querySelector('#camera');
			playerEl.addEventListener('collide', function(e) {
				console.log('Player has collided with body #' + e.detail.body.id);

				e.detail.target.el;  // Original entity (playerEl).
				e.detail.body.el;    // Other entity, which playerEl touched.
				e.detail.contact;    // Stats about the collision (CANNON.ContactEquation).
				e.detail.contact.ni; // Normal (direction) of the collision (CANNON.Vec3).
			});
``` 
maybe i have a wrong way of using the aframe-physics-system components?

**Comment by donmccurdy** [comment]
I see... that looks right. And you're using aframe-extras v2.0.1 or higher?

**Comment by yuicer** [comment]
no 
```
"dependencies": {
    "aframe": "^0.7.0",
    "aframe-animation-component": "^3.2.5",
    "aframe-physics-system": "^2.1.0",
    "autoprefixer": "^7.1.5",
    "axios": "^0.16.2",
    "connect-history-api-fallback": "^1.4.0",
    "copy-webpack-plugin": "^4.1.1",
    "express": "^4.16.2",
    "three": "^0.87.1",
    "vue": "^2.5.2",
    "vue-router": "^2.8.1",
    "vue-template-compiler": "^2.5.2",
    "vuex": "^2.5.0"
  },
```

**Comment by yuicer** [comment]
here is the demo，could it be fixed or am i wrong?
`http://yuicer.com/aframe_demo/`

**Comment by dwagner4** [comment]
I loaded your code into another server but pulled the physics component
from the CDN (version 2.1) instead of using your local copy.

<script src="//
cdn.rawgit.com/donmccurdy/aframe-physics-system/v2.1.0/dist/aframe-physics-system.min.js
"></script>

It worked great.  Regretfully the server was in a temporary container which
I'm not leaving up, but try it on yours.  Looks like it works to me.

I like the idea of making a First Person Camera by adding a static-body
child.

**Comment by yuicer** [comment]
@dwagner4 
coz i can't access to the 
`http://cdn.rawgit.com/donmccurdy/aframe-physics-system/v2.1.0/dist/aframe-physics-system.min.js`
maybe i'm in china?.....
the physics component was copied from the github, the dist folder 
 `https://github.com/donmccurdy/aframe-physics-system`
and i also download your pinball project , it still print out nothing.
but, what's the difference between them?

**Comment by donmccurdy** [comment]
There was a bug until October 13th where collide events did not fire - if you downloaded the file before that, you have the buggy copy. More recent versions like 2.1.0 should be right.

**Comment by yuicer** [comment]
@donmccurdy @dwagner4 
it did work after i update the  aframe-physics-system package to the latest version
thanks a lot for your precious time.
and i'm sorry this is a stupid issue.............
thanks a lot!

**Comment by donmccurdy** [comment]
No worries — sorry about the bug in the previous version.

And thanks @dwagner4 for the tip!
