### ISSUE TITLE
physics sytem errors when attached via mixin to an entity that is removed

### ISSUE THREAD

**Issue by MilesMcBain** [donmccurdy/aframe-physics-system#73]
I get this error: 
```
Uncaught TypeError: Cannot read property 'isScene' of null
    at i.module.exports.syncFromPhysics (aframe-physics-system.js:15832)
    at i.step (aframe-physics-system.js:15870)
    at o.tick (aframe-physics-system.js:16859)
    at HTMLElement.value (a-scene.js:592)
    at HTMLElement.value (a-scene.js:634)
    at bind.js:12
```
Immediately after removeChild is called on an entity that has `dynamic-body` added via a mixin. 

I wrote a component to remove the entity from the scene after a specified number of ticks (`ttl`). I have created a reprex involving it and aframe-physics-system here: https://descriptive-riverbed.glitch.me. `success.html` shows the entity removal working with physics when not added via mixin, `failure.html` is identical code with `ttl` and `dynamic-body` added to an entity directly.

**Comment by wmurphyrd** [comment]
I've seen something similar if an entity gets removed from the scene before the body finished loading.

**Comment by donmccurdy** [comment]
This seems to be an issue in a-frame, `.remove()` is never called on the component if that component was created through a mixin. Moving the issue here: https://github.com/aframevr/aframe/issues/3339
