### ISSUE TITLE
Using "shape: hull" produces an error

### ISSUE THREAD

**Issue by letoast** [donmccurdy/aframe-physics-system#76]
aframe-physics-system.js:14840 : Uncaught TypeError: Cannot read property 'length' of undefined
Line 14840:  ` if (!geometry || !geometry.vertices.length) return null;
`

The problem is that the script doesn't check if the geometry that it receives is of type Geometry or BufferGeometry. BufferGeometry doesn't have the property array ".vertices". I solved it by adding an if statement and converting a possible BufferGeometry to Geometry:

`      temp = getGeometry(object),`
`      geometry = new THREE.Geometry();`
`  if (temp instanceof THREE.BufferGeometry){`
`    geometry.fromBufferGeometry(temp);`
`  }`
`  if (!geometry || !geometry.vertices.length) return null;`

**Comment by donmccurdy** [comment]
Thanks! Is there an example (model, Codepen, Glitch, etc.) you could share?

**Comment by letoast** [comment]
Here you go: https://jsfiddle.net/boobiepls/60wx2rft/

You can see that the torus has no collision geometry and if you open up the browser's console you can see the error.
