### ISSUE TITLE
Detecting when a body stops moving

### ISSUE THREAD

**Issue by sirkitree** [donmccurdy/aframe-physics-system#77]
Hi there. Thank you for this component so much. It's been useful to me in so many ways!

I'm trying to detect when a dynamic body stops moving. The body is using the `distance` constraint in `0 gravity` and also `sleepy` from @wmurphyrd's [aframe-physics-extras](https://github.com/wmurphyrd/aframe-physics-extras).
```html
<a-sphere radius=".1" 
    dynamic-body 
    constraint="type: distance; target: #parent-sphere; distance: 1" 
    sleepy></a-sphere>
```

This causes the body to retain it's distance correctly when touched and slow down fairly quickly. When it stops, I'd like to detect it's position and do something with that.

I've successfully detected the `collide` event, but I don't see anything in there that allows me to know if the body has stopped moving, or I can't tell if it's the end of the event or the beginning. I assume beginning.

**successful execution**
```js
      thisPlanetEl.addEventListener('collide', function(e) {
        var bodyId = e.detail.body.el.getAttribute('id');
        var targetId = e.detail.target.el.getAttribute('id');
        console.log(bodyId +' collides with '+ targetId);
      });
```

I've tried to detect the 'stateremoved' event, which is a technique that the `sleepy` component uses as well (seemingly successfully) but which my code does not.

**failure to execute**
```js
      thisPlanetEl.addEventListener('stateremoved', function(e) {
        console.log(e);
        if (e.detail.state === 'hovered' || e.detail.state === 'grabbed') {
          console.log(e.detail.state);
        }
      });
```

Is there another way? Should the `stateremoved` method work?

**Comment by wmurphyrd** [comment]
You could listen for the CANNON.js `'sleep'` event, assuming you're using the local driver option in `aframe-physics-system`

https://github.com/schteppe/cannon.js/blob/569730f94a1d9da47967a24fad0323ef7d5b4119/src/objects/Body.js#L486

**Comment by sirkitree** [comment]
Thanks, I've tried the following:

```js      
      thisPlanetEl.addEventListener('sleep', function(e) {
        console.log('sleep', e);
      });
```
as well as
```js
      thisPlanetEl.addEventListener('sleepy', function(e) {
        console.log('sleepy', e);
      });
```

I can see the event listener get attached to the element, but it never fires, even after moving the body with a controller and seeing it slow down / sleep. At this point I'm wondering if the constraint  is somehow blocking events other than `collide` from firing... 

I tried removing the constraint on the body, but still only the `collide` event listener fires. So it doesn't seem to be that...

Here's the prototype if you get a chance and want to check out the code: https://aframe-ephem.glitch.me/ -  I'll keep messing with it.

**Comment by wmurphyrd** [comment]
Oh sorry for not pointing this out - when using the CANNON api directly, A-Frame conventions like events being connected to and bubbling up entities no longer hold. Try `thisPlanetEl.body.addEventListener` (but not until after the body has been loaded, detected via the 'body-loaded' A-Frame event on the entity)

[Here's an example](https://glitch.com/edit/#!/short-sun?path=index.html:1:0)

Another option would be stick with `'grab-end'` (or `'stateremoved'` for `'grabbed'` state) but use a `'setTimeout'` to delay the execution for a moment so the entity has had time to come to rest. The timing wouldn't be exact, but I bet you couldn't find something good enough

**Comment by sirkitree** [comment]
Thanks! After some marginal success with that, I found that I should actually be making changes based on the `componentchanged` event for my purposes (need to change position of other planets when the position of one changes) It's not super smooth, but I think it'll serve my purposes. I learned much through this exchange, so thank you!
