### ISSUE TITLE
Physics breaks when moving dynamic in tick()

### ISSUE THREAD

**Issue by AhambaliJ** [donmccurdy/aframe-physics-system#78]
The `dynamic-body` physics seems to be broken when moving object with dynamic body using `body.position.set`.

The object seems to have to be vibrating up and down when the object is "held" for a period of time, the vibrating behaviour seems to escalate further as the object is move up along the `y-axis`.

The y-position of the object seems to contain 2 point at the same time as seen in the figure below.

<img width="364" alt="aframe physic 1" src="https://user-images.githubusercontent.com/13192228/34759018-91d29986-f614-11e7-8d44-fb4b9f9476fb.png">

I assume that the gravity physics is still acting on the object even when it is manipulated by the user thus creating such behaviour. 

Right now I'm trying to add an invisible entity at the point which the object is held and constraint the object to the entity when grabbing the object. I will update the result later.

Thank you all.

Here is the link for the demo
https://torpid-crayon.glitch.me/

**Comment by wmurphyrd** [comment]
What effect are you trying to achieve? If it is just a simple grabbing operation, that it best handled by creating a constraint. See [aframe-extras grab](https://github.com/donmccurdy/aframe-extras/blob/master/src/misc/grab.js) or [super-hands grabbable](https://github.com/wmurphyrd/aframe-super-hands-component/blob/master/reaction_components/prototypes/physics-grab-proto.js)

Distinct from grabbing, I've also used the [following pattern](https://github.com/wmurphyrd/adit/blob/master/js/plot-interactions.js#L219-L224) to reset the position of a `dynamic-body` without breaking behavior:

```
entity.setAttribute('position', {x: 0, y: 0, z: 0})
entity.components['dynamic-body'].syncToPhysics()
```

**Comment by AhambaliJ** [comment]
It's just a simple grabbing operation. Just that I don't want to create any constraint so that it is much cheaper in terms of performance. I've created another version using constraint, the application lags when it runs using a mobile phone.

I've approached Don at Slack and he suggested me to open an issue. I'll try using your resolution in my code.

**Comment by donmccurdy** [comment]
@AhambaliJ What device(s) do I need to see your demo? I tried opening on desktop but couldn't look around.

I wouldn't expect much of a difference in terms of performance when using a constraint, because either way the object is still being simulated by the physics engine. Both @wmurphyrd and I have implemented grabbing before, and have used constraints to do that.

> It seems that your resolution breaks the ability to grab completely.

His suggestion is a good way of setting the position of the object and making sure the physics engine knows about that change, but what you have with `el.body.position.set(x,y,z)` is also fine. I don't think that's the issue here.

**Comment by AhambaliJ** [comment]
@donmccurdy  Sorry for that, forgot to inform that you need to hold down Alt key to look around, grab by mousedown and release by mouseup.

I tried using constraint on another project: https://rose-sale.glitch.me/ . If what you're saying is true in term of performance then I should not get the lag when using mobile phone, but when tested by multiple devices (by my friends), the VR application still lags.

**Comment by donmccurdy** [comment]
Also note that your previous demo has a typo here:

```js
// no effect
item.components['dynamic-body'].syncToPhysics;
// correct
item.components['dynamic-body'].syncToPhysics();
```

I think that's why the ball jankily glitches and falls while being held.

**Comment by AhambaliJ** [comment]
I've fixed the typo inside of the demo. The only changes that I can see that the ball stopped moving instead of being moved around. Tested it both on desktop and mobile.

**Comment by donmccurdy** [comment]
I think something is confused here: you're modifying `el.body` (the physics element) and then calling sync _to_ physics, which overwrites it. You'll want one of these, to ensure things are in sync:

```js
entity.setAttribute('position', grabbedPosition);
entity.components['dynamic-body'].syncToPhysics();
```

or perhaps:

```js
item.body.position.copy(grabbedPosition);
entity.components['dynamic-body'].syncFromPhysics();
```

**Comment by AhambaliJ** [comment]
Thank you @donmccurdy .

Your first suggestion works, which is what I was trying to do in the first place.
The second suggestion doesn't, I guess that it would be because of they snc() overriding the modified el.body.

Thank you again.
