### ISSUE TITLE
this.body.updateProperties is not a function

### ISSUE THREAD

**Issue by InfiniteLee** [donmccurdy/aframe-physics-system#84]
from this commit: https://github.com/donmccurdy/aframe-physics-system/commit/dc42a66b626c604498bc3dd11cf1272d4c3d8527

That method isn't defined in `body` in https://github.com/donmccurdy/cannon.js/tree/v0.6.2-dev1

**Comment by donmccurdy** [comment]
Oops, yeah that's only available when running in a worker. Fixed: https://github.com/donmccurdy/aframe-physics-system/commit/590fffef305997bdac4aa38ee6ef8079eb43adb3
