### ISSUE TITLE
Build and update to the latest code version.

### ISSUE THREAD

**Issue by calderonsteven** [donmccurdy/aframe-physics-system#86]
I noticed that the /dist files are outdated based on the latest changes. 
I'm not seeing this https://github.com/donmccurdy/aframe-physics-system/blob/08a98a4c3d77c4c38a1fa27067aa0d894447902e/src/components/body/body.js#L145 change in the distributable files.

Thanks man, and awesome work!

**Comment by donmccurdy** [comment]
Updated, thanks 🙂
