### ISSUE TITLE
Conflict with movement-controls component

### ISSUE THREAD

**Issue by iancarnation** [donmccurdy/aframe-physics-system#89]
Howdy, 

It seems as though the [movement-controls](https://github.com/donmccurdy/aframe-extras/tree/master/src/controls) component from your [a-frame extras](https://github.com/donmccurdy/aframe-extras) encounters an issue while trying to use the physics system.

I'm getting an `Cannot read property 'x' of null` error from the controls' `updateVelocity` function.

Example here: https://controls-physics-conflict.glitch.me/

Thanks for any help!

**Comment by firewaller** [comment]
Same here +1

**Comment by donmccurdy** [comment]
Fixed by https://github.com/donmccurdy/aframe-extras/commit/a4bc425483998db0c27c35f3ee3701929c60fa50 in aframe-extras v4.0.1, thanks!

>  If it helps, I get the same error when I press spacebar using the "jump-ability" without physics-system enabled.

The `jump-ability` component does depend on physics, and gives errors without it.
