### ISSUE TITLE
Roatated collision

### ISSUE THREAD

**Issue by flamingfox101** [donmccurdy/aframe-physics-system#96]
Collisions don't rotate along with models automatically, it would be nice to have that.

**Comment by flamingfox101** [comment]
This would be under enhancement, I just don't know how to mark it.

**Comment by flamingfox101** [comment]
#

**Comment by donmccurdy** [comment]
Could you explain what you mean by “rotated collision”, or give an example? I’m not sure I understand.

**Comment by flamingfox101** [comment]
When putting in a gltf model, and adding a static body it looks something like this:
```
<a-entity static-body
	grabbable dropppable
	shadow="cast: true; recive: false;"
	gltf-model="#cat_gate"
	position= "-6.5 0 7.75" scale="65 50 50" 
	rotation="0 0 0">
	
</a-entity>
```
If i wanted to rotate it i'd rotation like:
```
rotation="0 90 0"
```
But I've noticed the auto collision doesn't match with the rotated version, instead you have to it like this:
```
<a-entity
	shadow="cast: true; recive: false;"
	gltf-model="#cat_gate"
	position= "10.25 0 4" scale="65 50 50" 
	rotation="0 90 0"
	body="type:static; mass:5; shape: none;"
		shape__bottom="shape: box;
		halfExtents: 0.015 0.025 0.002;
		offset: 0 0.015 0;">
	
</a-entity>
```
It would be nice to be able to have the auto collision rotate along with the gltf or whatever you choose to use.

**Comment by donmccurdy** [comment]
I think you're describing the same thing as https://github.com/donmccurdy/aframe-physics-system/issues/93 — the shape used for physics simulation is not rotated to match the visible mesh? Going to close this as a duplicate and track this issue there, if so.
